### ISSUE TITLE
Markdown rendering

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1438]
OP: @loopDelicious https://github.com/postmanlabs/postman-app-support/issues/5269

Throughout the [Postman docs](https://learning.getpostman.com/docs), kramdown needs to be scooched to markdown.

![markdown](https://user-images.githubusercontent.com/17693714/46161868-91379c80-c23b-11e8-9ae8-596819d592c8.png)

* Rendering inline code (attached screenshot)
* Rendering target blanks, and markdown hyperlinks
* Relative links are hardcoded v6, and redirects are not yet active, so relative links are 404

**Comment by captchadex** [comment]
• Rendering target blanks, and markdown hyperlinks
• Relative links are hardcoded v6, and redirects are not yet active, so relative links are 404

The above two issues are fixed. The only remaining one is "Rendering inline code" which needs the kramdown to be removed.

**Comment by loopDelicious** [comment]
Here's another example:
<img width="1003" alt="screen shot 2018-10-01 at 2 43 41 pm" src="https://user-images.githubusercontent.com/17693714/46317659-9886df00-c588-11e8-91a5-3042cd592989.png">

**Comment by loopDelicious** [comment]
@ArifPMan Should probably be fixed whenever the OLD docs is redirected to the NEW pages (since fixing this for the NEW code will break the OLD code).

Examples below of inline code and table formatting that is broken in the NEW learning center:
- https://learning.getpostman.com/docs/postman/environments_and_globals/variables#accessing-variables-in-the-request-builder
- https://learning.getpostman.com/docs/postman/collections/data_formats#importing-curl

**Comment by kaustavdm** [comment]
Looks like the existing ones have been fixed. I will close this issue for now. We can open new issues as and when we spot inconsistencies. Much of #1737 and #1738 should address these anyway.
