### ISSUE TITLE
Importing swagger with folders by path

### ISSUE THREAD

**Issue by iamkarlson** [postmanlabs/postman-docs#1485]
Hey, I'm trying to import OpenAPI spec to the postman and getting just a bunch of requests without a name or anything unique for each. So it's quite difficult to distinguish which one is what. Do you have any option for imports which can tell postman to group importing requests by URL path?

**Comment by kaustavdm** [comment]
@iamkarlson We have multiple fixes for the OpenAPI importer coming up in next versions. I am closing this issue since this is a product issue that is better tracked in the [postmanlabs/postman-app-support](https://github.com/postmanlabs/postman-app-support) issue queue. Please feel free to point out documentation inconsistencies/requests in this repo.
