### ISSUE TITLE
Provide installation instructions after user downloads the app

### ISSUE THREAD

**Issue by harryi3t** [postmanlabs/postman-docs#1960]
Reported originally here: https://github.com/postmanlabs/postman-app-support/issues/7581

After downloading Postman for Linux, we don't communicate well to the users about what should be done next.

Slack shows platform-specific instructions post download.
### Ubuntu
![image](https://user-images.githubusercontent.com/5207331/68576208-b31dce00-0493-11ea-9d47-7b7fb39e322b.png)
### Fedora
![image](https://user-images.githubusercontent.com/5207331/68576225-bb760900-0493-11ea-950d-fe44fdcfd5e6.png)

**Comment by SueSmith** [comment]
Will add this to PR #1969

**Comment by arlemi** [comment]
I think we can close this one since details have been added to the Learning Center: https://learning.postman.com/docs/postman/launching-postman/installation-and-updates/#installing-postman-on-linux

Will keep postmanlabs/postman-app-support#7581 opened for improvements to the installation flow rather than documentation.
