### ISSUE TITLE
Incorrect link on the `Migrate your team to Postman 7.0` pop-up

### ISSUE THREAD

**Issue by DannyDainton** [postmanlabs/postman-docs#1967]
A user reported that the `Learn more` link on the _Migrate your team to Postman 7.0_ is redirecting to a 404 page on the Learning Center site.

![image](https://user-images.githubusercontent.com/17089546/68691467-b1273e00-056b-11ea-8df9-02e65a2cff3b.png)

The in-app link is redirecting to: 

https://learning.getpostman.com/doc/postman_pro/managing_postman_pro/roles_and_permissions

It looks like the link should be going here:

https://learning.getpostman.com/docs/postman-pro/managing-pro/roles-and-permissions/

As well as the underscores, the URL path looks to have changed slightly from `managing_postman_pro` to `managing-pro`

**Comment by cyrielle-hada** [comment]
Same report from Support - the in-app prompt for the user to downgrade to version 6 takes him to this URL - https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/migrating_to_v7/#team-user-on-postman-v7 which lands on a 404. 

instead of https://learning.getpostman.com/docs/postman-pro/managing-pro/migrating-to-v7/#update-to-postman-v7

**Comment by SueSmith** [comment]
@cyrielle-hada k have added this one too, must investigate whether we can use wildcards or something to ideally fix the whole section..
