### ISSUE TITLE
Working with datafiles : CSV don't pass tests

### ISSUE THREAD

**Issue by Rom1deTroyes** [postmanlabs/postman-docs#2187]
Following the `Working with data files` example (src/pages/docs/postman/collection-runs/working-with-data-files.md), I ran in trouble with the CSV part.

It's seems that `jsonData.form.foo` is parsed as a `string`, and `data.value` is parsed as a `number`, so the assertion `jsonData.form.foo === data.value` is `false`.

With the json datafile, both are parsed as `string`, so there is no problem.

In the preview window, CSV value has no `"` :
![image](https://user-images.githubusercontent.com/8625432/74724072-f8dcf600-523b-11ea-971a-3076a8261647.png)
The JSON preview got them :
![image](https://user-images.githubusercontent.com/8625432/74724439-8e788580-523c-11ea-8765-5b9e5ff63c45.png)

I've try to debug this with a quick typeof :
```javascript
var jsonData = JSON.parse(responseBody);
tests['Response has data value :' + typeof jsonData.form.foo + "==="+ typeof data.value + " ?"] = jsonData.form.foo === data.value
```

With CSV datafile (all red) :
```
Response has data value :string===number ? | AssertionError: expected false to be truthy
```

With JSON datafile (all green) :
```
Response has data value :string===string ?
```

(Postman v7.18.0 on Win10)

**Comment by SueSmith** [comment]
Hi there, could you clarify the issue here - is it with the documentation or the app itself? This is the Postman Learning Center repo, if the issue is with the Postman app you might want the app support repo https://github.com/postmanlabs/postman-app-support/

**Comment by Rom1deTroyes** [comment]
Following the documentation steps at https://learning.postman.com/docs/postman/collection-runs/working-with-data-files/ don't work for me, so I think the issue is for the Learning Center repo.

The example provide a screenshot with all tests passing using the csv file provided :
![image](https://assets.postman.com/postman-docs/working_with_datafiles/request_debug_tooltip.png)

Here is what I got when running the collection with the csv file :
![image](https://user-images.githubusercontent.com/8625432/74930861-c0295200-53de-11ea-8a53-4b6b5e387947.png)

And what is given with the quick debug I made above :
![image](https://user-images.githubusercontent.com/8625432/74931074-3a59d680-53df-11ea-8a2e-88220d8a1b8d.png)

The JSON file used in the `legacy-documentation/v5/postman/collection_runs/working_with_data_files.md` file works (because Json file and Json request are parsed the same).

**Comment by Rom1deTroyes** [comment]
Note that if one change the csv file to quote the values, it works :
```csv
path, value
post, "1"
post, "2"
post, "3"
post, "4"
```

![image](https://user-images.githubusercontent.com/8625432/74932149-66765700-53e1-11ea-8095-483caf57657a.png)

So if there a way to modify the [CSV asset](https://assets.postman.com/postman-docs/58702574.csv), I'll be happy to contribute with a PR :-)

**Comment by SueSmith** [comment]
Thanks so much for providing this extra info @Rom1deTroyes and PRs are always much appreciated..! 😄 

@DannyDainton You have a much better handle on the issues with this page than me, could you weigh in here?

**Comment by DannyDainton** [comment]
Hey @Rom1deTroyes, 

Thanks for raising this - The example Collection and the images on that particular page in the documentation is "dated" to be honest. 

I'd like to change the scenario to POST the data in a JSON payload rather than via a form. As the collection in the example is using the old test syntax, I've updated this in this Collection.

https://www.getpostman.com/collections/831c54ca605b0c63fbdb

You can import this in your own Postman app and try it out with the CSV and JSON datafiles from the example. We already have the new images locally so it would just be a case of updating the copy on the Learning Center document if this collection is good for you.

As per it not currently parsing the CSV numbers in the form data scenario and converting these to strings, I think this doesn't look quite right and I've reached out to our wonderful developers to let them know, from here I will raise an issue if one is needed.

**Comment by arlemi** [comment]
@Rom1deTroyes Were you able to give a go at the collection posted by Dany?
