### ISSUE TITLE
no html <img> tags

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2323]
Our Markdown in src/pages/docs should not contain <img> tags without any <alt tags>.

In order to increase accessibility those tags should all be changed to Markdown images with alt tags:

[![alt text](https://assets.postman.com/postman-docs/<file name>.png)](https://assets.postman.com/postman-docs/<file name>.png)

**Comment by SueSmith** [comment]
Just a wee note that we're also looking into options for specifying image size in markdown (that's why we've used img tags in some places so if we manage that the image markdown can include dimensions too). Getting the alt text in all images would still be great regardless of if/when we figure out the sizing though!

**Comment by ch264** [comment]
I just checked the Markdown docs and they say that HTML img tag should be used for resizing images:
https://www.markdownguide.org/basic-syntax/#html

Therefore, we should keep doing that. There is no easy way to add css tags to Markdown. 

I agree with @SueSmith that we need alt tags for all images.

**Comment by HarshaVardhan16** [comment]
Hey,
I am interested in working. Guide me, so that I can understand the project better.

**Comment by vishwajeetraj11** [comment]
Hey, Can anyone please guide me on how to contribute. I have developed 1 API using Postman. 
Here is the link: https://documenter.getpostman.com/view/10515433/Szf539Xx
I also made a website using the same: https://natours-web-application.herokuapp.com/ ( it will take time to load since the app goes to sleep after 30 mins of inactivity --happens on heroku).

**Comment by soumy47** [comment]
Hey, I would like to work on this issue. Can you suggest ways to get started?

**Comment by ch264** [comment]
Hey @soumy47, all our assets start with 'https://assets.postman.com'.
I would recommend running a search for 'https://assets.postman.com' in the docs channel and if you see any assets without a <alt> tag, to add one.

Here is the Markdown syntax for alt tags [![alt text](https://assets.postman.com/postman-docs/.png)](https://assets.postman.com/postman-docs/.png) 🚀

**Comment by soumy47** [comment]
How do I reproduce the issue?@ch264

**Comment by soumy47** [comment]
how can I reproduce the issue?@ch264

**Comment by soumy47** [comment]
how do I reproduce the issue?please help me @ch264

**Comment by soumy47** [comment]
How I reproduce the issue?@ch264

**Comment by arjungarg07** [comment]
Hey @ch264 , I would like to work upon this issue.

**Comment by Cronus1007** [comment]
@ch264 Shall I implement this issue.

**Comment by jkonrath-postman** [comment]
I just did a quick search and it looks like all of our img elements have alt tags now.
