### ISSUE TITLE
Searching for "export" leads to 404

### ISSUE THREAD

**Issue by yiantseng** [postmanlabs/postman-docs#2371]
When I search export, this page pops up as the first result:
https://learning.postman.com/docs/postman/collections/importing-and-exporting-data/

It goes to a 404.

<img width="914" alt="Screen Shot 2020-05-06 at 11 23 26 AM" src="https://user-images.githubusercontent.com/4899445/81195615-15134800-8f8c-11ea-9a5f-c244681a5700.png">

I believe it should point to this page: https://learning.postman.com/docs/postman/collections/data-formats/#exporting-postman-data

**Comment by SueSmith** [comment]
Ah sorry for the confusion, this is a page that's not published yet (it's indexed because it's in the beta site), I don't believe we have the ability to only search the prod site.. it'll sort itself out within a couple of days though..! p.s. it's actually this page renamed https://learning.postman.com/docs/postman/collections/data-formats/

**Comment by HarshaVardhan16** [comment]
Hey,
I would like to contribute. Please guide me.

**Comment by HeroicHitesh** [comment]
@yiantseng @SueSmith I checked the links and it seems to be working fine now, so I believe this issue can be closed now.

**Comment by loopDelicious** [comment]
Confirmed this appears to be working now.
