### ISSUE TITLE
List Bootcamp in Developer Resources

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2620]
We mention Bootcamp in a lot of webinars as Additional Learning Resources. I would expect those similar resources to be listed in Developer Resources of the side navigation. Bootcamp is the most relevant resource. And if / when we can deeplink to it in the Postman Web, we should.

**Comment by HeroicHitesh** [comment]
@loopDelicious @SueSmith I would like to work on this, let me know if I can start working on it.

**Comment by loopDelicious** [comment]
@HeroicHitesh - we don't have a great place scoped out yet for this new addition (since it doesn't really fit into the existing pages in that section). Will need some additional soak time on this one.

**Comment by HeroicHitesh** [comment]
Sure @loopDelicious take your time, and let me know when it's available for working on. 
I have one suggestion based on this discussion, we can have labels like - `Status: On-hold`, `Status: Discussion reqd`, `Status: Available`, `Status: Assigned`, `Status: Needs Testing`, `Status: Needs Review`, etc. in order to help new contributors to focus better on the available issues.

**Comment by jkonrath-postman** [comment]
We've got this linked in the introduction and navigating sections now.
