### ISSUE TITLE
Use more inclusive nomenclature in documentation, whitelist -> allowlist

### ISSUE THREAD

**Issue by kevinswiber** [postmanlabs/postman-docs#2837]
Hi there.  Let's adopt more inclusive language in the documentation.

* [whitelist](https://github.com/postmanlabs/postman-docs/search?l=Markdown&q=whitelist) -> allowlist

_EDIT: The request to rename the branch from `master` to `main` has been moved to #2838, per https://github.com/postmanlabs/postman-docs/issues/2837#issuecomment-776153136._

**Comment by tristandenyer** [comment]
I see this as two projects since one is handled by Content team and the other by Engineering:
* Eng will need to make the switch for renaming the branch and be sure we update the CONTRIBUTING.md documentation as well (`master` mentioned there.)
* Content team will need to review `whitelist` usage across the Product documentation.

@kevinswiber would you mind splitting this out into two Issues? That way we can handle them individually. Thx!

**Comment by kevinswiber** [comment]
@tristandenyer Thank you!  Done!

**Comment by jkonrath-postman** [comment]
@kevinswiber let me look into this and sync with the content design team to make sure they're on the same page before I change it globally.

**Comment by jkonrath-postman** [comment]
I'm moving this internally so I can be linked to the other changes going on in Jira. See TW-84 to follow.
